config/routes.rb
LanceBrownDesign::Application.routes.draw do
  resources :projects

  get "users/new"

  root :to => "pages#home"

  match '/home', :to => 'pages#home'
  match '/profile', :to => 'pages#profile'
  match '/portfolio', :to => 'projects#grid'
  match '/database', :to => 'projects#index'
  match '/taglines', :to => 'pages#taglines'

end

app/models/project.rb
class Project < ActiveRecord::Base
  def next
      self.class.first :conditions => ["id > ?", self.id], :limit => 1,  :order => "id asc"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }

  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def profile
  end

  def project
  end

  def taglines
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def grid
    @projects = Project.all

    respond_to do |format|
      format.html # grid.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="append-bottom">
<h1 class="first span-7 prepend-1" id="Logo"> 
  <%= link_to "LanceBrown", home_path, :id => 'Orange' %><%= link_to "Design:", home_path, :id => 'Gray' %> 
</h1>
<nav class="span-15 prepend-1 last">
<ul>
  <li>&nbsp;</li>
  <li><%= link_to 'portfolio', portfolio_path %></li>
  <li><%= link_to 'profile', profile_path %></li>
  <li><%= link_to 'contact', 'mailto:lance@lancebrowndesign.com' %></li>
</ul>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lance Brown Design</title>
    <%= render 'shared/includes' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="span-15 prepend-9 last">
  <h2>
    Creative thinking, <br /> 
    strategically executed. 
  </h2>
  <h2>
    Strategic thinking, <br />
    creatively executed.
  </h2>
</div>

app/views/pages/portfolio.html.erb
<div class="span-16 prepend-8">
    <%= link_to image_tag("thumb_buy-inCover.jpg", :size => "75x75", :alt => "Hilcorp Energy Brochure"), "portfolio/buyIn.htm" %>
    <%= link_to image_tag("thumb_tonkawaLogo.jpg", :size => "75x75", :alt => "Tonkawa Farms Logo"), "portfolio/tonkLogo.htm" %>
    <%= link_to image_tag("thumb_liskow-2.jpg", :size => "75x75", :alt => "Liskow & Lewis Ads"), "portfolio/liskowAds.htm" %> 
    <%= link_to image_tag("thumb_topTen.jpg", :size => "75x75", :alt => "Hilcorp Energy Poster"), "portfolio/topTen.htm" %>
    <%= link_to image_tag("thumb_boscoLabel.jpg", :size => "75x75", :alt => "Bosco Bites Label"), "portfolio/boscoLabel.htm"	%>
    <%= link_to image_tag("thumb_johnSpaldCover.jpg", :size => "75x75", :alt => "Johnson Spalding Brochure"), "portfolio/johnsonSpalding.htm" 		%>
    <%= link_to image_tag("thumb_collings.jpg", :size => "75x75", :alt => "Collings Guitar Ads"), "portfolio/collings.htm" %>
    <%= link_to image_tag("thumb_cowLogo.jpg", :size => "75x75", :alt => "Becks Prime Milkshake Logo"), "portfolio/milkshakeLogo.htm" %>
    <%= link_to image_tag("thumb_coverCalendar.jpg", :size => "75x75", :alt => "Hilcorp Energy Calendar"), "portfolio/hilcorpCalendar.htm" %>
    <%= link_to image_tag("thumb_s&wBlocks.jpg", :size => "75x75", :alt => "Scott & White Building Graphic"), "portfolio/s&wBlocks.htm" %>
    <%= link_to image_tag("thumb_cccLogo.jpg", :size => "75x75", :alt => "Cindy Carlson Company Logo"), "portfolio/cccLogo.htm" %>
    <%= link_to image_tag("thumb_hlpLogo.jpg", :size => "75x75", :alt => "HLP Holdings Logo"), "portfolio/hlpLogo.htm" %>
    <%= link_to image_tag("thumb_detroitLogo.jpg", :size => "75x75", :alt => "Detroit Center Logo"), "portfolio/detroitLogo.htm" %>
    <%= link_to image_tag("thumb_barryCard.jpg", :size => "75x75", :alt => "Julie Barry Identity"), "portfolio/barryCard.htm" %>
    <%= link_to image_tag("thumb_kelseyWeb.jpg", :size => "75x75", :alt => "Virginia Kelsey Website"), "portfolio/virginiaKelsey.htm" %>
    <%= link_to image_tag("thumb_v&eLogo.jpg", :size => "75x75", :alt => "Vinson & Elkins Logo"), "portfolio/v&eLogo.htm" %>
    <%= link_to image_tag("thumb_frederickWeb.jpg", :size => "75x75", :alt => "Frederick Website"), "portfolio/frederickBook.htm"	%>
    <%= link_to image_tag("thumb_hilcorpLogo.jpg", :size => "75x75", :alt => "Hilcorp Logotype"), "portfolio/hilcorpLogo.htm" %>
    <%= link_to image_tag("thumb_75l&l.jpg", :size => "75x75", :alt => "Liskow & Lewis"), "portfolio/l&lAnniversary.htm" %>
</div>

app/views/pages/profile.html.erb
<aside class="span-7 prepend-1 first" id="CompanyList">
A partial client listing includes:
<ul>
  <li>&nbsp;</li>
  <li>Becks Prime Restaurants</li>
  <li>Collings Guitars</li>
  <li>Cordúa Restaurants</li>
  <li>the Galleria</li>
  <li>Hilcorp Energy Company</li>
  <li>Hines</li>
  <li>Kellogg Brown &amp; Root</li>
  <li>Oil &amp; Gas Journal</li>
  <li>Reliant Energy </li>
  <li>Scott &amp; White Memorial Hospital</li>
  <li>Scott &amp; White Health Plan</li>
  <li>Smith International</li>
  <li>St. Luke’s Episcopal Hospital</li>
  <li>Vinson &amp; Elkins</li>
  <li>Weatherford International</li>
</ul>
</aside>

<article class="span-15 prepend-1 last" id="Profile">
<p>
Established in 1982 Lance Brown Design provides clients with design, writing and marketing services that are intelligent, creative and effective.
</p>

<p>
Creating work that is stylish and engaging the firm’s experience includes the design and production of annual reports, corporate identity programs, <%= link_to "company taglines", taglines_path %>, brochures, electronic media and print advertising.
</p>

<p>
Lance’s work has been recognized for its design excellence by The Art Directors Club of New York, Communication Arts Magazine, Print Magazine, and a variety of other professional organizations. Lance is a former director and past president of the American Institute of Graphic Arts/Texas.
</p>

<ul id="ContactInfo">
  <li>Lance Brown Design</li>
  <li>Houston, Texas</li>
  <li>(713) 858-1967</li>
</ul>
</article>

app/views/pages/project.html.erb
<h1>Pages#project</h1>
<p>Find me in app/views/pages/project.html.erb</p>

app/views/pages/taglines.html.erb
<div class="span-7 prepend-1 first" id="CompanyList">
  A few of the taglines I've developed for my clients:
</div>
<div class="span-15 prepend-1 last" id="Profile">
  <% Project.all.each do |project| %>
    <% if project.tagline %>
      <p>
      <span class="orangeType">
        <%= project.tagline %>
      </span> 
      <br /> 
      <%= project.name %> <br /> 
      <br /> 
      </p>
    <% end %>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br />
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/grid.html.erb
<div class="span-13 prepend-9 append-2">
  <% @projects.each do |project| %>
    <% if project.description %>
      <%= link_to image_tag("#{project.thumbnail}", :size => "75x75", :alt => "${project.description}"), project %>
      <% i = 0 %>
      <% i = i + 1 %>
      <% if (i.divmod(5) == 0) || (i.divmod(3) ==0) %>
        <br />
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Thumbnail</th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= image_tag project.image, :size => "100x100" if project.image %></td>
      <td><%= image_tag project.thumbnail if project.thumbnail %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="first span-7 prepend-1 prepend-top description">
  <%= @project.description %> <br />
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', :action => 'grid' %>
  <% project = @project.next %>
  <% unless project.nil? %>
    <% while !project.image %>
      <% project = project.next %>
    <% end %>
    | <%= link_to('Next', project)%>
  <% end %>
</div>
<div class="span-13 prepend-3 last">
  <%= image_tag "#{@project.image}", :alt => "#{@project.name}" %>
</div>

app/views/shared/_includes.html.erb
<%= stylesheet_link_tag "special/reset", "typography", "grid", "forms", :cache => true, :media => "screen, projection" %>
<!-- Load Custom Stylesheet Last -->
<%= stylesheet_link_tag "special/custom", :media => "screen, projection" %>
<% if false %>
<%= stylesheet_link_tag "special/print", :media => "print" %>
<!--[if lt IE 8]>
<%= stylesheet_link_tag "special/ie" %>
<![endif]-->

  <%= javascript_include_tag :defaults %>
<% end %>
<%= csrf_meta_tag %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>